= mill-moduledefs
:toc-placement: preamble
:toc:
:version: 0.10.9-alpha-1

A Scalac compiler plugin to support Mill modules.

== About

The Mill build tool module structure is highly tied to the organizational structure of the Scala programming language.
Project modules are modelled as Scala ``object``s, Module targets are modelled as Scala ``def``s.

Mill targets are also modelled as free applicatives, which among other things makes the Mill task graph introspectable. To hide some boilerplate code needed to nicely write tasks like ``def``s, Mill uses some Scala macros and a Scalac compiler plugin.

In this project, you'll find the compiler plugin and some shared code.

== Project Layout

This project contains two modules:

* `moduledefs` - Some shared code to be used in the Mill classpath. The `artifactName` is `mill-moduledefs`.
* `moduledefs/plugin` - A Scalac compiler plugin to be used when compiling Mill projects. The `artifactName` is `scalac-mill-moduledefs-plugin`.

== Development and Releases

This code is expected to change rarely.

It should be especially kept stable within the same Mill major version.

=== Publishing

Publishing is automated via GitHub Actions and implemented in the `publishToSonatype` command.

[source,scala]
----
def publishToSonatype(
    sonatypeCreds: String,
    gpgArgs: String = PublishModule.defaultGpgArgs.mkString(","),
    dryRun: Boolean = false,
    artifactsFile: Option[String] = None
): Command[Unit]
----

=== Re-publish for a new Scala Release
:example-version: 0.10.9
:example-scala-version: 2.13.10

The most frequently expected changes are releases for newer Scala version.
This is especially needed, as compiler plugins are tied to the exact Scala compiler version.

Hence, this build aims to be flexible enough, to release an already tagged version for newer Scalac releases after the fact.

As an example, to release an already published version `{example-version}` for a new Scala version `{example-scala-version}`, follow these steps:

. Create a branch `release-{example-version}` from the git tag `{example-version}`.

. Add the new Scala version to the build setup. Make sure you don't change the actual code, so it stays compatible to the original tag.

. Add a file `PUBLISH_ONLY` containing a selector for the artifacts to publish. If you need more than one selector, place each on a new line.
+
.Example file `PUBLISH_ONLY`
----
moduledefs.plugin[2.13.10].publishArtifacts
----

. Commit your changes.

. Tag your commit with `{example-version}-for-{example-scala-version}`. This will trigger the `publish-sonatype` workflow in GHA.

. If appropriate, update the Readme/Changelog in the `main` branch.

== Download

Artifacts of this project are released to Maven Central.

[source,scala,subs="verbatim,attributes"]
----
// The shared library
ivy"com-lihaoyi::mill-moduledefs:{version}"
// The compiler plugin
ivy"com-lihaoyi:::scalac-mill-moduledefs-plugin:{version}"
----

== License

This project is published under the https://mit-license.org/[MIT License].

== Changelog

=== 0.10.9-alpha-1 - 2022-10-17

Initial release from this repository. Intended for testing only.

=== Older Releases

Older versions of this project were developed in the Mill git repository and were packaged as ordinary Scala artifact `mill-moduledefs` (without the full Scala version suffix). Refer to  https://github.com/com-lihaoyi/mill/issues/2035[issue #2035], to learn why we split the projects.
